### ISSUE TITLE
Fails in Node.js v7 due to dependency failure

### ISSUE THREAD

**Issue by Trott** [Swaagie/stackexchange#10]
I'm testing the Node.js v7 beta and the `stackexchange` package fails because `devnull` errors out. If they publish current master as v0.0.13 or newer, `stackexchange` should start working again. See https://github.com/observing/devnull/issues/5

However, if you don't want to depend on that happening and if you want to make sure `stackexchange` continues to work, maybe consider switching logging package or mechanism? Node.js v7 is tentatively scheduled to be released for realz on October 25, I think.

**Comment by nwhitmont** [comment]
I have published a working (& actively maintained) fork of this module here: https://www.npmjs.com/package/stackexchange-node

**Comment by Trott** [comment]
This is fixed in 1.0.0-1. `npm install stackexchange@next` to get it right now, or wait until 1.0.0 is released which should be soon.
