### ISSUE TITLE
Question: How to change the site parameter, to search on other websites?

### ISSUE THREAD

**Issue by karanaggarwal1** [Swaagie/stackexchange#14]
Hey, thanks for the amazing work on the package. Just one question, how does one go about changing the site parameter which is used to search within the different websites of the stack exchange network. Currently, I am just attaching a site parameter in the filter I am using to get the contents however the results I am obtaining are solely from the stackoverflow website. Please let me know if there's something different is to be done to achieve this.
Thanks.

**Comment by Trott** [comment]
Set it in the `options` for the constructor rather than in the `filter`. Here's how to retrieve questions from cooking.stackexchange.com rather than StackOverflow.

```js
var stackexchange = require('stackexchange');

var options = { site: 'cooking.stackexchange', version: 2.2 };
var context = new stackexchange(options);

var filter = {
  key: 'YOUR_API_KEY',
  pagesize: 50,
  sort: 'activity',
  order: 'asc'
};

// Get all the questions (http://api.stackexchange.com/docs/questions)
context.questions.questions(filter, function(err, results){
  if (err) throw err;
  
  console.log(results.items);
  console.log(results.has_more);
});
```

I'll close this, but feel free to comment or re-open if this doesn't answer your question.

**Comment by Trott** [comment]
(Actually, I'll re-open this as there's probably a doc improvement to be made for this. PR welcome!)

**Comment by karanaggarwal1** [comment]
Hey Trott, thanks for the comment, but is it better to fix the site parameter in the beginning itself? What if we wanted to make several requests using the same object. I have submitted a PR Regarding this. Please have a look.

**Comment by Trott** [comment]
I think this can be closed because https://github.com/Swaagie/stackexchange/pull/15 was merged. If I'm wrong, please re-open or leave a comment. Thanks.
