### ISSUE TITLE
Comments for questions and answers 

### ISSUE THREAD

**Issue by c-schuhmann** [Swaagie/stackexchange#32]
It would be nice if you could get a list of comments for questions and answers. I think the implementation would be similar to the `answers` method implementation in `questions.js`.
 See: https://api.stackexchange.com/docs/comments-on-answers

I would also create a pull request later, if adding such a feature would be okay.

**Comment by Trott** [comment]
If you want to add the code, tests, and documentation required, it would be welcome.

Do you have a need for this feature or is it just something that seems like it ought to be there and would be nice to have?
