### ISSUE TITLE
Documentation: How to get a specific question?

### ISSUE THREAD

**Issue by gajus** [Swaagie/stackexchange#6]
Getting a specific question via URL is:

```
http://api.stackexchange.com/2.2/questions/' + questionId + '?site=stackoverflow&filter=withbody
```

It is not clear how to do it using this SDK.

**Comment by Swaagie** [comment]
Sorry for the late reply, must have missed. Yeah documentation is lacking a bit, however https://github.com/Swaagie/stackexchange/blob/master/lib/methods/questions.js#L13 should be adequate to help you right now. Any PR's to improve the docs would be welcome.

**Comment by Trott** [comment]
> Getting a specific question via URL is:
> 
> ```
> http://api.stackexchange.com/2.2/questions/' + questionId + '?site=stackoverflow&filter=withbody
> ```
> 
> It is not clear how to do it using this SDK.

Five years later, I'm guessing you either figured out the answer to your question or else don't care anymore. But even if so, for anyone else coming along:

This appears to be asking "If I know the question ID, how do I retrieve the question?"

The answer (or at least one possible answer) is:

```javascript
'use strict';

var stackexchange = require('stackexchange');

var questionIds = ['27054920'];

var stackexchange = require('stackexchange');

var options = { version: 2.2 };
var context = new stackexchange(options);
var filter = {filter: 'withBody'};

context.questions.questions(filter, callback, questionIds);

function callback(err, data) {
  if (err) throw err;
  console.log(data);
}
```

Not the unconventional function signature where the question IDs come *after* the callback. Conventionally, the callback is the last thing in the function signature.

I've been contemplating doing a breaking change to make it more like this:

```javascript
var filter = {filter: 'withBody'};
var ids = ['27054920'];
var options = { filter: filter, ids: ids };

context.questions.questions(options, callback);
```

I'm guessing I'm the only person using this module with any regularity at this point, but feedback welcome.
