### ISSUE TITLE
Cannot use with Stack Enterprise (SO for companies)

### ISSUE THREAD

**Issue by ericis** [Swaagie/stackexchange#64]
It is not possible to connect to a Stack Enterprise API endpoint instead of public StackOverflow.

While the "./lib/stackexchange.js" file allows the developer to provide custom configuration settings:

https://github.com/Swaagie/stackexchange/blob/24a849e6d279d64ce24c83a8454424fc5b500e11/lib/stackexchange.js#L19-L22

The queries in "./lib/query.js" rely on the statically bundled configuration of the package:

https://github.com/Swaagie/stackexchange/blob/24a849e6d279d64ce24c83a8454424fc5b500e11/lib/query.js#L21-L26

**Comment by Trott** [comment]
Which of those settings would you need to change to use Stack Enterprise API?

**Comment by Trott** [comment]
Would it just be the hostname or would it be something else?

**Comment by Trott** [comment]
This seems to work for me:

```
var stackexchange = require('stackexchange');

var options = { api: 'example.stackexchange.com' };
var context = new stackexchange(options);
```

I admit that having the hostname configuration option called `api` is not intuitive. We can add a more intuitive alias if that makes sense to do.
