### ISSUE TITLE
Snyk says stackexchange's request dependency has 4 vulnerabilities in it.

### ISSUE THREAD

**Issue by m4bwav** [Swaagie/stackexchange#7]
I'm not sure if what it says is true but I figured you want to see the report.
Probably just need to update the request version or something.

Report:
"? Low severity vulnerability found on hawk@0.13.1
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:hawk:20160119
- from:stackexchange@0.3.0 > request@2.21.0 > hawk@0.13.1
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

? Medium severity vulnerability found on qs@0.6.6
- desc: Denial of Service (Memory Exhaustion)
- info: https://snyk.io/vuln/npm:qs:20140806
- from: stackexchange@0.3.0 > request@2.21.0 > qs@0.6.6
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

? Medium severity vulnerability found on qs@0.6.6
- desc: Denial of Service (Event Loop Blocking)
- info: https://snyk.io/vuln/npm:qs:20140806-1
- from: stackexchange@0.3.0 > request@2.21.0 > qs@0.6.6
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

? Medium severity vulnerability found on request@2.21.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:request:20160119
- from: stackexchange@0.3.0 > request@2.21.0
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options."

**Comment by Swaagie** [comment]
Thanks for checking, this might be due to the request dependency, that version is fairly autodated atm. I'll update it to a later version, which should perhaps resolve the issue

**Comment by m4bwav** [comment]
Thanks for updating the dependency, Synk says the vulnerabilities are gone.
